name: Call Workflow and Get Arifact

on:
  workflow_dispatch:

jobs:
  Call-Workflow-and-Get-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Call Workflow
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
          gh workflow run main.yaml --repo Kbs56/test-gh-action
          sleep 3s
          run_id=$(gh run list --workflow main.yaml --repo Kbs56/test-gh-action --limit 1 --json databaseId | jq -r '.[0].databaseId')
          echo $run_id
          gh run watch $run_id --repo Kbs56/test-gh-action
          gh run download $run_id --repo Kbs56/test-gh-action --dir artifact
          ls -lart
          cd artifact
          ls -lart
          cat world.txt
