name: Call Workflow and Get Arifact

on:
  workflow_dispatch:

jobs:
  Call-Workflow-and-Get-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Call Workflow
        id: get-ids
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
          gh workflow run main.yaml --repo Kbs56/test-gh-action
          sleep 3s
          run_id=$(gh run list --workflow main.yaml --repo Kbs56/test-gh-action --limit 1 --json databaseId | jq -r '.[0].databaseId')
          echo $run_id
          gh run watch $run_id --repo Kbs56/test-gh-action
          gh run download $run_id --repo Kbs56/test-gh-action
          cd my-artifact
          app_name=$(jq -r '.app_name' test.json)
          app_version=$(jq -r '.app_version' test.json)
          echo "app_name=$app_name" >> $GITHUB_OUTPUT
          echo "app_version=$app_version" >> $GITHUB_OUTPUT

      - name: Echo Outputs
        run: |
          echo ${{ steps.get-ids.outputs.app_name }}
          echo ${{ steps.get-ids.outputs.app_version }}

      - name: Set as Vars in Target Repo
        run: |
          gh variable set APP_NAME --body ${{ steps.get-ids.outputs.app_name }} --repo Kbs56/test-gh-action
          gh variable set APP_VERSION --body ${{ steps.get-ids.outputs.app_version }} --repo Kbs56/test-gh-action
